/**
 *      Nama    : St. Hatijah H. Ilyas
 *      Stambuk : 13020180061
 *      Tanggal : 18 Juni 2020
 *      Waktu   : 14.09 WITA
 */

import java.awt.Frame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

public class NilaiMhs extends javax.swing.JFrame {
    DefaultTableModel model;
    InterfaceNilaiMhs profileServices;
    List record = new ArrayList();
    int baris;
    //String pindah;
    //hj    int i=1;

   /* NilaiMhs(String udahPindah) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        this.pindah=udahPindah;
    }*/
    /** Creates new form NilaiMhs */
    
    private void setTable(){
        try {
            record = profileServices.getAll();
            Object data[][] = new Object[record.size()][6];
            int x = 0;
            for (Iterator it = record.iterator(); it.hasNext();) {
                mahasiswa p = (mahasiswa) it.next();
                data[x][0] = p.getNama();
                data[x][1] = p.getTgsM();
                data[x][2] = p.getTgsP();
                data[x][3] = p.getUts();
                data[x][4] = p.getUas();
                data[x][5] = p.getKehadiran();
                x++;
            }
        Object[] field = {"Nama Mahasiswa", "Tugas Mandiri","Tugas Proyek","Nilai UTS", "Nilai UAS", "Kehadiran", "Nilai Akhir","Nilai Huruf"};
        model = new DefaultTableModel(field,0);
        tabel.setModel(model);
        JTableHeader th = tabel.getTableHeader();
        th.setReorderingAllowed(false);
        tabel.setRowHeight(20);
    }catch (SQLException ex) {
            Logger.getLogger(NilaiMhs.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private String calculate(String... utm){
        for(int i=0; i<utm.length; i++){
            if(utm[i].isEmpty()){
                utm[i] = "0";
            }
        }
        double t1=0, t2=0, t3=0, t4=0, t5=0;
        for (int i=0; i<utm.length; i++){
            double cv = Double.valueOf(utm[i]);
            switch(i){
                case 0:
                    t1=cv*0.2;
                    break;
                case 1:
                    t2=cv*0.2;
                    break;
                case 2:
                    t3=cv*0.2;
                    break;
                case 3:
                    t4=cv*0.25;
                    break;
                case 4:
                    t5=cv*0.15;
                    break;
                default:
                    break;
            }
        }
        double jumlah=t1+t2+t3+t4+t5;
        double as = Math.round(jumlah);
        String cvJumlah = indexOF(as);
        return cvJumlah;
    }
    
    public String indexOF(double b){
        String hsl;
        if(b%1==0){
            hsl=String.valueOf(b).substring(0, String.valueOf(b).lastIndexOf("."));
        }else{
            hsl=String.valueOf(b);
        }
        return hsl;
    }
    
    private String calAbjad(String jumlah){
        String nilai="";
        double b=Double.valueOf(jumlah);
        if(b>85){
            nilai="A";
        }else if(b<=85 && b>=81){
            nilai="A-";
        }else if(b<=80 && b>=76){
            nilai="B+";
        }else if(b<=75 && b>=71){
            nilai="B";
        }else if(b<=70 && b>=66){
            nilai="B-";
        }else if(b<=65 && b>=61){
            nilai="C+";
        }else if(b<=60 && b>=51){
            nilai="C";
        }else if(b<=50 && b>=45){
            nilai="D";
        }else if(b<45){
            nilai="E";
        }
        return nilai;
    }
    
    public NilaiMhs() {
        initComponents();
        KoneksiDb.getConnection();
        
        this.setLocationRelativeTo(null);
        profileServices = new ImplNilaiMhs();
        //Edit.setEnabled(false);
        //Hapus.setEnabled(false);
        setTable();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMhs = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTM = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtUTS = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtUAS = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        HitungSimpan = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        txtKeh = new javax.swing.JTextField();
        Edit = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.white);

        jPanel2.setBackground(java.awt.Color.pink);
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel1.setText("MENGHITUNG NILAI MAHASISWA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel2.setText("PROGRAM STUDI TEKNIK INFORMATIKA");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        jPanel3.setBackground(java.awt.Color.white);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Nama Mahasiswa");

        txtMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMhsActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Tugas Mandiri");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Tugas Proyek");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Nilai UTS");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Nilai UAS");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Kehadiran");

        HitungSimpan.setFont(new java.awt.Font("Tekton Pro", 1, 16)); // NOI18N
        HitungSimpan.setForeground(java.awt.Color.magenta);
        HitungSimpan.setText("Hitung dan Simpan");
        HitungSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungSimpanActionPerformed(evt);
            }
        });

        Refresh.setFont(new java.awt.Font("Tekton Pro", 1, 16)); // NOI18N
        Refresh.setForeground(java.awt.Color.magenta);
        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });

        jPanel4.setBackground(java.awt.Color.pink);

        jScrollPane1.setBackground(java.awt.Color.pink);
        jScrollPane1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        tabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 986, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 211, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        Edit.setFont(new java.awt.Font("Tekton Pro", 1, 16)); // NOI18N
        Edit.setForeground(java.awt.Color.magenta);
        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        Hapus.setFont(new java.awt.Font("Tekton Pro", 1, 16)); // NOI18N
        Hapus.setForeground(java.awt.Color.magenta);
        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });

        Keluar.setFont(new java.awt.Font("Tekton Pro", 1, 16)); // NOI18N
        Keluar.setForeground(java.awt.Color.magenta);
        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtUTS, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtUAS, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(HitungSimpan)
                                        .addGap(49, 49, 49)
                                        .addComponent(Refresh)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTM, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(txtTP))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(txtKeh, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(340, 340, 340))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Edit)
                .addGap(38, 38, 38)
                .addComponent(Hapus)
                .addGap(382, 382, 382)
                .addComponent(Keluar)
                .addGap(236, 236, 236))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtUTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtKeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HitungSimpan)
                    .addComponent(Refresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Edit)
                    .addComponent(Hapus)
                    .addComponent(Keluar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 987, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        int[] pilih = tabel.getSelectedRows();
        if(pilih.length > 0){
            for(int i = pilih.length-1; i >=0; i--){
                model.removeRow(pilih[i]);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Pilih Data yang ingin Dihapus");
        }
        reset();
    }//GEN-LAST:event_HapusActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        try {
            // TODO add your handling code here:
            mahasiswa p = new mahasiswa();

            if (txtMhs.getText().equals("") && txtTM.getText().equals("") && txtTP.getText().equals("") && txtUTS.getText().equals("") && txtUAS.getText().equals("") && txtKeh.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Silahkan Isi Data Yang Akan Diubah");
            } else {
                p.setNama(txtMhs.getText());
                p.setTgsM(Integer.parseInt(txtTM.getText()));
                p.setTgsP(Integer.parseInt(txtTP.getText()));
                p.setUts(Integer.parseInt(txtUTS.getText()));
                p.setUas(Integer.parseInt(txtUAS.getText()));
                p.setKehadiran(Integer.parseInt(txtKeh.getText()));
                profileServices.update(p);
                ambil_data_tabel();
                JOptionPane.showMessageDialog(this, "Data Berhasil Diubah");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Data Gagal Diubah");
        }
    }//GEN-LAST:event_EditActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        Edit.setEnabled(true);
        Hapus.setEnabled(true);
        //Add.setEnabled(false);
        int i=tabel.getSelectedRow();
        if(i>=-1){
            txtMhs.setText(model.getValueAt(i, 0).toString());
            txtTM.setText(model.getValueAt(i, 1).toString());
            txtTP.setText(model.getValueAt(i, 2).toString());
            txtUTS.setText(model.getValueAt(i, 3).toString());
            txtUAS.setText(model.getValueAt(i, 4).toString());
            txtKeh.setText(model.getValueAt(i, 5).toString());
        }
    }//GEN-LAST:event_tabelMouseClicked

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_RefreshActionPerformed

    private void HitungSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungSimpanActionPerformed
        // TODO add your handling code here:
        String MS = txtMhs.getText();
        String tgs = txtTM.getText();
        String tgs1 = txtTP.getText();
        String tgs2 = txtUTS.getText();
        String tgs3 = txtUAS.getText();
        String tgs4 = txtKeh.getText();

        if(MS.isEmpty()){
            JOptionPane.showMessageDialog(this, "Masukkan Nama Terlebih Dahulu");
            txtMhs.requestFocus();
        }else{
            String[] data= {tgs, tgs1, tgs2, tgs3, tgs4};
            String jml = calculate(data);
            Object[] data2 = {MS, tgs, tgs1, tgs2, tgs3, tgs4, jml, calAbjad(jml)};
            model.addRow(data2);
        }
        reset();
    }//GEN-LAST:event_HitungSimpanActionPerformed

    private void txtMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMhsActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        // TODO add your handling code here:
        int reply= JOptionPane.showConfirmDialog(null, "Yakin Ingin Keluar?", "Konfirmasi Keluar Aplikasi", JOptionPane.YES_NO_OPTION);
        if(reply==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_KeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NilaiMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NilaiMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NilaiMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NilaiMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NilaiMhs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Edit;
    private javax.swing.JButton Hapus;
    private javax.swing.JButton HitungSimpan;
    private javax.swing.JButton Keluar;
    private javax.swing.JButton Refresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField txtKeh;
    private javax.swing.JTextField txtMhs;
    private javax.swing.JTextField txtTM;
    private javax.swing.JTextField txtTP;
    private javax.swing.JTextField txtUAS;
    private javax.swing.JTextField txtUTS;
    // End of variables declaration//GEN-END:variables

    private void reset(){
        txtMhs.setText("");
        txtTM.setText("");
        txtTP.setText("");
        txtUTS.setText("");
        txtUAS.setText("");
        txtKeh.setText("");
    }
    
    public void isiFields() {
        mahasiswa p = (mahasiswa) record.get(baris);
        txtMhs.setText(String.valueOf(p.getNama()));
        txtTM.setText(String.valueOf(p.getTgsM()));
        txtTP.setText(String.valueOf(p.getTgsP()));
        txtUTS.setText(String.valueOf(p.getUts()));
        txtUAS.setText(String.valueOf(p.getUas()));
        txtKeh.setText(String.valueOf(p.getKehadiran()));
    }
    
    public void ambil_data_tabel() {

        tabel.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                baris = tabel.getSelectedRow();
                if (baris != -1) {
                    isiFields();
                }
            }
        });
    }
    
}

